# Generated by Django 4.0.3 on 2022-05-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiPhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaiphuongtien', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienso', models.CharField(max_length=20)),
                ('tenphuongtien', models.CharField(max_length=50)),
                ('chusohuu', models.CharField(max_length=100)),
                ('loaiphuongtien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baidoxe_dangki.loaiphuongtien')),
            ],
        ),
    ]
