# Generated by Django 4.0.4 on 2022-05-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baidoxe_dangki', '0003_phuongtien_thaydoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phuongtien',
            name='thaydoi',
        ),
    ]
