# Generated by Django 4.0.4 on 2022-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidoxe_dangki', '0004_remove_phuongtien_thaydoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennguoidung', models.CharField(max_length=100)),
                ('matkhau', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
