# Generated by Django 4.0.4 on 2022-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidoxe_dangki', '0005_nguoidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='tentaikhoan',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
