# Generated by Django 4.0.3 on 2022-06-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidoxe_dangki', '0006_nguoidung_tentaikhoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuPhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienso', models.CharField(max_length=20)),
                ('tenphuongtien', models.CharField(max_length=50)),
                ('chusohuu', models.CharField(max_length=100)),
                ('thoigian', models.DateTimeField()),
                ('loaiphuongtien', models.CharField(max_length=50)),
                ('thoigianra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
